### ISSUE TITLE
No preview?

### ISSUE THREAD

**Issue by ray-x** [dcampos/cmp-snippy#1]
Seems there is no preview for the snippet.
Is it caused by completion_item.documentation missing?

**Comment by dcampos** [comment]
Exactly, `completion_item.documentation` was missing. I've added basic support for previewing snippets. It's also necessary to update nvim-snippy. Please let me know if something still doesn't work.

**Comment by moshiur-raj** [comment]
@dcampos  I'm  facing the same issue. snippy does not provide any previews, however lsp snippet expansion works fine. nvim-cmp has recently made some breaking changes. maybe the plugin needs to be updated?
