### ISSUE TITLE
Getting started + readme typo?

### ISSUE THREAD

**Issue by ekaj2** [dcampos/cmp-snippy#5]
Hey @dcampos I'm trying nvim-snippy out and it seems that I'll need this as well to integrate since I use nvim-cmp?

Also, it looks like the README has a small typo here:

```
Plug 'dcampos/nvim-snippy'
```

Shouldn't this be `cmp-snippy`?

**Comment by dcampos** [comment]
> I'm trying nvim-snippy out and it seems that I'll need this as well to integrate since I use nvim-cmp?

Indeed. This plugin is needed for showing Snippy completions with nvim-cmp. Check the README for how to configure it, and also nvim-cmp's README contains some info on how to integrate with different snippet engines. Please let me know if you need some specific information.

> Shouldn't this be cmp-snippy?

Thanks for pointing out the mistake. Fixed.
